language: node_js

node_js:
  - "0.8"
  - "0.10"

services:
  - redis-server
  - memcached

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev

install:
  - npm install

before_script:
  - npm install -g grunt-cli

script:
  - npm test

env:
  - EXPECT_CACHED=0
  - EXPECT_CACHED=1 REDIS_URL=127.0.0.1
  - EXPECT_CACHED=1 MEMCACHED_URL=127.0.0.1
